[bar/test]
monitor = eDP-1
width = 100%
height = 30
dock = true
lineheight = 10
background = #ff184f
foreground = #000000
linecolor = #c51850
font-0 = envypn:pixelsize=13;0

modules-center = tailscript
modules-right = intervalscript

[module/tailscript]
type = custom/script
exec = xtitle -s
tail = true

[module/intervalscript]
type = custom/script
exec = echo %counter%..
interval = 1

; vim:ft=dosini
