#!/usr/bin/env bash

source bootstrap.sh

include utils/log.sh
include utils/x11.sh

bootstrap::finish

function main
{
  if [[ $# -lt 2 ]]; then
    log::err "Usage: $0 [-k|--kill-all] <config> <bar_name> [bar_name...]"; exit 1
  fi

  if [[ "$1" == "-k" ]] || [[ "$1" == "--kill-all" ]]; then
    killall -9 -q lemonbuddy lemonbuddy_wrapper lemonbar &>/dev/null ; shift
  fi

  local config="$1" ; shift
  local -a bars=("${@}")

  if ! [[ -e "$config" ]]; then
    log::err "Configuration file not found: $config"; exit 2
  fi

  for bar in ${bars[*]}; do
    if ! grep -q "\[bar/${bar}\]" "$config"; then
      log::err "The bar '${bar}' is not defined in the configuration, skippinng..."; continue
    fi

    log::info "Launching bar '${bar}'"

    monitor="$(lemonbuddy "$bar" -c "$config" -d monitor)"

    if ! x11::monitor_connected "$monitor"; then
      log::err "The bar '${bar}' is configured for disconnected monitor '${monitor}', skipping..."
      continue
    fi

    wmname=$(lemonbuddy "$bar" -c "$config" -w)

    if [[ -z "$wmname" ]]; then
      log::err "Failed to get WM_NAME for the bar '${bar}', skipping..."
      continue
    fi

    lemonbuddy "$bar" -c "$config" &
  done

  echo "$config" "${bars[@]}" > "$XDG_CONFIG_HOME/lemonbuddy/.runargs"
}

main "$@"
