#!/usr/bin/env bash

size_gap=5
size_border=1

polybar_config="$LOCAL_ETC"/polybar/oldconfs/i3.conf
polybar_bars=(i3_top)

if xrandr | grep -q "HDMI-1 connected"; then
  polybar_bars+=(i3_top_hdmi)
  polybar_bars+=(i3_bottom_hdmi)
fi

theme::pre_startup()
{
  xrandr --output HDMI-1 --auto --above eDP-1

  if xrandr | grep -q "HDMI-1 connected"; then
    b_wmname="$(polybar i3_bottom_hdmi -c "$polybar_config" --print-wmname)"
    b_height="$(polybar i3_bottom_hdmi -c "$polybar_config" --dump=height)"
    b_offset="$(polybar i3_bottom_hdmi -c "$polybar_config" --dump=offset_y)"
    b_border="$(polybar i3_bottom_hdmi -c "$polybar_config" --dump=border-top)"
    xdrawrect HDMI-1 bottom 100% 3 0 $((b_height+b_offset+b_border+3)) '#ff000000' effectline-bottom &
  fi
}

theme::post_startup()
{
  xdrawrect eDP-1 top 100% 3 0 27 '#ff000000' effectline-top "$(polybar i3_top -c "$polybar_config" --print-wmname)" &

  if xrandr | grep -q "HDMI-1 connected"; then
    t_wmname="$(polybar i3_top_hdmi -c "$polybar_config" --print-wmname)"
    t_height="$(polybar i3_top_hdmi -c "$polybar_config" --dump=height)"
    t_offset="$(polybar i3_top_hdmi -c "$polybar_config" --dump=offset_y)"
    t_border="$(polybar i3_top_hdmi -c "$polybar_config" --dump=border-bottom)"
    xdrawrect HDMI-1 top 100% 3 0 $((t_height+t_offset+t_border)) '#ff000000' effectline-bottom &
  fi
}
