#!/usr/bin/env bash

size_border=1
size_gap=5

padding_top=32
padding_bottom=0
padding_left=0
padding_right=0

color_focused_border="#fba922"
color_normal_border="#2e2e2e"
color_active_border="#2e2e2e"
color_presel_feedback="#aaaaaa"

setting_borderless_monocle='false'

lemonbuddy_config="$CURRENT_THEME/lemonbuddy"
lemonbuddy_bars=(top)

if xrandr | grep -q "HDMI-1 connected"; then
  lemonbuddy_bars+=(external_bottom)
fi

theme::post_bspwmrc()
{
  xdrawrect eDP-1 top 100% 3 0 27 '#ff000000' effectline-top "$(lemonbuddy top -c "$lemonbuddy_config" --print-wmname)" &

  if xrandr | grep -q "HDMI-1 connected"; then
    bspc config -m HDMI-1 top_padding 0
    bspc config -m HDMI-1 bottom_padding $padding_top
  fi

  xdrawrect HDMI-1 bottom 100% 3 0 27 '#ff000000' effectline-bottom "$(lemonbuddy external_bottom -c "$lemonbuddy_config" --print-wmname)" &
}
