#!/usr/bin/env bash

source bootstrap.sh

include utils/polybar.sh
include utils/x11.sh

bootstrap::finish

size_border=1
size_gap=5

padding_top=0
padding_bottom=0
padding_left=0
padding_right=0

color_focused_border="#fba922"
color_normal_border="#333333"
color_active_border="#333333"
color_presel_feedback="#555555"

setting_borderless_monocle='true'
setting_gapless_monocle='true'
setting_single_monocle='false'

polybar_config="$CURRENT_THEME/polybar"
polybar_bars=(top bottom)
