#!/usr/bin/env bash

source bootstrap.sh

include utils/lemonbuddy.sh

bootstrap::finish

size_gap=5
size_border=1

lemonbuddy_config="${XDG_CONFIG_HOME}/lemonbuddy/config.i3"
lemonbuddy_bars=(top)

if x11::monitor_connected "HDMI-1"; then
  lemonbuddy_bars+=(external_bottom)
fi

function theme::pre_startup {
  :
}

function theme::post_startup {
  xsetroot -bg '#1d1d1d' -fg '#2a2a2a' -bitmap "${CURRENT_THEME}/tile.xbm"
}
