#!/usr/bin/env bash

source bootstrap.sh

include utils/polybar.sh

bootstrap::finish

size_gap=1
size_border=2

polybar_config="$CURRENT_THEME/polybar"
polybar_bars=(top bottom)

function theme::post_startup {
  : # xsetroot -bg '#1d1d1d' -fg '#2a2a2a' -bitmap "${CURRENT_THEME}/tile.xbm"
}
