#!/usr/bin/env bash
wid="$1"
class="$2"
instance="$3"

if xprop -id "$id" WM_NAME | grep \"floatme\"; then
  echo "state=floating"
elif [[ "$class" == "chromium" ]]; then
  role=$(xprop -id "$wid" | awk '/WM_WINDOW_ROLE/ {print $3}' | tr -d '"')

  case "$role" in
    app)
      echo "state=floating"
      xwincenter "$(xdo id -a Authy)"
    ;;
  esac
elif [[ "$class" == "Steam" ]]; then
  echo "state=floating"
elif [[ "$class" == "Eclipse" ]] || [[ "$class" == "Java" ]]; then
  wm_type=$(xprop -id "$wid" | awk '/_NET_WM_WINDOW_TYPE_SPLASH/ {print $3}')

  if [[ "$wm_type" == "_NET_WM_WINDOW_TYPE_SPLASH" ]]; then
    echo "state=floating"
  fi
fi
