#!/usr/bin/env bash
mkdir -p "${XDG_CACHE_HOME}"/openbox
rm "${XDG_CACHE_HOME}"/bspwm/std{out,err} >/dev/null 2>&1
run_count=0
while (( ++run_count )); do
  echo "---- STARTUP $(date +"%Y-%m-%d %H:%M:%S") ----" >> "${XDG_CACHE_HOME}"/bspwm/stdout
  echo "---- STARTUP $(date +"%Y-%m-%d %H:%M:%S") ----" >> "${XDG_CACHE_HOME}"/bspwm/stderr
  export BSPWM_COUNTER=$run_count
  bspwm >>"${XDG_CACHE_HOME}"/bspwm/stdout 2>>"${XDG_CACHE_HOME}"/bspwm/stderr || break
done
