#!/usr/bin/env sh

# Configure outputs
if stat -c %N /etc/X11/xorg.conf.d/20-gpu.conf 2>/dev/null | egrep -q "(optimus|nvidia).conf"; then
  xrandr --setprovideroutputsource modesetting NVIDIA-0
  xrandr --auto
elif stat -c %N /etc/X11/xorg.conf.d/20-gpu.conf 2>/dev/null | egrep -q intel.conf && gpu-state; then
  gpu-change off
fi

mon_internal="eDP-1"
mon_external="HDMI-1"

xrandr -q | grep -q "eDP-1" || mon_internal="eDP1"
xrandr -q | grep -q "HDMI-1" || mon_external="HDMI1"

if xrandr -q | grep -q "^$mon_external connected"; then
  xrandr --output $mon_external --auto --above $mon_internal --set audio force-dvi
fi

# set the screen server to blank at 1h
xset s 3600 3600
xset s noblank

# Turn off power management
xset -dpms
